### ISSUE TITLE
Typo in ConsolePlatformExtensions (NPM)

### ISSUE THREAD

**Issue by AavaGames** [ANU-CHEEKI-BREEKI/com.anupackages.debugconsole#8]
For #if UNITY_IOS and #if UNITY_STANDALONE. It references an undefined class ConsolePlatform instead of TargetPlatforms.

Imported in Unity version 2022.3.9f1 through NPM

**Comment by ANU-CHEEKI-BREEKI** [comment]
yeah... sorry for that 😔😔😔

it already fixed in latest commit of main branch 
and it also fixed in unity store latest version

thanks for notifying me, 
i'll find some time soon to create releases everywhere where package can be taken from

and thanks for trying the package!😌

**Comment by AavaGames** [comment]
Oh no worries, I figured it was just something you forgot about on the NPM branch and used the asset store version after i posted the issue. I know the pains hahaha.

Been using the package for a week now and love it. Thanks so much for releasing it for free, I'd gladly give you a coffee if you have a donation page somewhere.

**Comment by ligofff** [comment]
Looks like not solved in 2.1.3
I imported it to 2023.2.17f through NPM today, and got error 

`Library\PackageCache\com.anupackages.debugconsole@2.1.3\Runtime\Scripts\IngameDebug\Console\ConsolePlatformExtensions.cs(19,30): error CS0103: The name 'ConsolePlatform' does not exist in the current context`
